### ISSUE TITLE
[BUG]Missing images and content

### ISSUE THREAD

**Issue by crogonint** [Jonwh25/larsenes#2]
WhiteWaterWorship.webp says it was located in some 'Imports' folder that I don't see..?

I'm still sifting through the module. The only thing I've noticed so far is that the KoboldRed token doesn't exist for me. ..?

Spoke too soon, all three Manor maps appear to be in the same 'Imports' folder.
Aged Goodberry Wine, Clockwork Orange

The link from COVER AND CREDITS skips over the TABLE OF CONTENTS.
Tooling Up, Maverick Gliders and Ambush are missing as separate sections.
The entire The Tower section, sub-pages and contents appears to be missing.

**Comment by Jonwh25** [comment]
I've updated the maps, KoboldRed token, goodberry wine, clockwork wyvern, and fixed the cover and credits skipping the table of contents.  Added in the missing sections.    Please update to 1.4

I do think I remember removing the tower sections.  If you go to install a new world you will see the Mad Biomancer's Tower. That is actually that portion of the adventure with a few changes.  Since you mentioned them missing I think I'll just go ahead and add them all back, just so you can make whatever world you want.

I know there are still a few things broken and I'm working through them.  So I'll keep this open while I work on them. 

Please note there is no basement level map. You'll either need to create that one yourself, see if there is one online somewhere, or wait for me to make that one. When I do I'll add it to this.

**Comment by Jonwh25** [comment]
Everything updated. Still need to add basement map, but will have to wait due to time.

**Comment by crogonint** [comment]
If you don't have time to do the basement map, you could share a sketch and your assets to do the basement with me, and I could put one together for you. 🙂 It's the least I could do when you were so quick to fix everything else. 🙂
